// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQIXaxhLh6zhlXM0IVyqiQ62Rh12GlKIY',
    appId: '1:95258763986:android:00e467355f6fa40c6bc30b',
    messagingSenderId: '95258763986',
    projectId: 'fir-flutter-b7c93',
    storageBucket: 'fir-flutter-b7c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5KER5gJTJXmyV0hgNzoZQrORM4SarH7k',
    appId: '1:95258763986:ios:3be6a09614c17b696bc30b',
    messagingSenderId: '95258763986',
    projectId: 'fir-flutter-b7c93',
    storageBucket: 'fir-flutter-b7c93.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXgiGLF94wIPeDvIoPjBu-SFYy1jcWmo',
    appId: '1:95258763986:web:3725080d66e136d66bc30b',
    messagingSenderId: '95258763986',
    projectId: 'fir-flutter-b7c93',
    authDomain: 'fir-flutter-b7c93.firebaseapp.com',
    storageBucket: 'fir-flutter-b7c93.appspot.com',
    measurementId: 'G-8608FB0799',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5KER5gJTJXmyV0hgNzoZQrORM4SarH7k',
    appId: '1:95258763986:ios:3be6a09614c17b696bc30b',
    messagingSenderId: '95258763986',
    projectId: 'fir-flutter-b7c93',
    storageBucket: 'fir-flutter-b7c93.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBXgiGLF94wIPeDvIoPjBu-SFYy1jcWmo',
    appId: '1:95258763986:web:5655fdd722889c2a6bc30b',
    messagingSenderId: '95258763986',
    projectId: 'fir-flutter-b7c93',
    authDomain: 'fir-flutter-b7c93.firebaseapp.com',
    storageBucket: 'fir-flutter-b7c93.appspot.com',
    measurementId: 'G-LEPX1SYBT0',
  );

}